### ISSUE TITLE
Chrome Extension: Double modal when transferring Armour and Weapons

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/DIM#10]
If a load out contains both armour and weapons, 2 modals are created, one over the top of the other.

The attached screenshot shows the top most modal for Armour:

![screen shot 2015-03-30 at 3 42 31 pm](https://cloud.githubusercontent.com/assets/19838/6905282/f0eb9d4c-d6f4-11e4-800c-27df5e0c0458.png)

**Comment by dasilva333** [comment]
Problem should be fixed as of 1.5.3 try it now and confirm issue is fixed please

**Comment by ssoriche** [comment]
All fixed, thanks again!
