### ISSUE TITLE
Gear not showing currents stats.

### ISSUE THREAD

**Issue by squiglybob13** [dasilva333/DIM#11]
When highlighting gear it doesn't show the current light level or stats of the specific item. For instance I have a maxed raid chest piece, however when I highlight it it just shows the light at 24/36 and it also shows 64 DIS/STR/INT where it can't have all three. Not a breaking issue but would be nice to see the correct stats for own gear.

**Comment by dasilva333** [comment]
Do you mean over the DestinyDB tooltip or the transfer pop up?

**Comment by squiglybob13** [comment]
Oh it must be the DB popup. It's just when you're hovering over your items
prior to transfer. This may be an issue with the DB tool if that's the case.

**Comment by dasilva333** [comment]
The DB popup should show you your weapon's burn, primary attack value (or defense for armor) and perks. Closing the ticket as I'm assuming it's not an issue. feel free to reopen the ticket and post a screenshot if you still think it's an issue.

**Comment by squiglybob13** [comment]
Yea nevermind it seems to just be an issue on my Desktop, which is strange...

**Comment by dasilva333** [comment]
Sorry the comment I made 3 days ago was incorrect I didn't implement armor but now I do find some screenshots here: exotic helmet: http://i.imgur.com/PUDIP4o.png
legendary helmet: http://i.imgur.com/ggZDLHe.png

**Comment by squiglybob13** [comment]
Yea that's the same thing happening with me. The defense rating is correct but the stats are just min.
Exotic Arms: http://i.imgur.com/SjymWX4.jpg
Legendary Chest: http://i.imgur.com/lH8JSod.jpg
