### ISSUE TITLE
Win 8 touch issues

### ISSUE THREAD

**Issue by Jdiaz199** [dasilva333/DIM#12]
I love your app. Only issue is I have a Surface Pro 2(this probably counts for any Win8 touch device) and I keep getting the "patience is a virtue" error when I attempt to move from one character to another or equip.  I also am not able to see the options to move ect. because the item description gets in the way.  I don't know if you are able to fix this but it would be great. Thanks for all your work!
edit for image [Imgur](http://i.imgur.com/y3LKijj.jpg)

**Comment by dasilva333** [comment]
option to disable the tooltips has been added under Settings as of 1.2.8 closing ticket as it has been fixed
