### ISSUE TITLE
incredibly small text size

### ISSUE THREAD

**Issue by coasterreal** [dasilva333/DIM#15]
On my Note 2 it's fairly small but I can understand that.

On my Samsung Note 10.1 2014 which has a 10" screen it's the same size as my phone. Makes it very difficult to read even with my very good vision. Can it scale to the device or can I choose text sizes? I posted a picture/screen shot of all the wasted space on reddit. Look for comment by same user name - coasterreal. From yesterday.

**Comment by Podlesnyy** [comment]
The same issue on my device.
I have Nexus 6
![screenshot_2015-04-01-14-16-01](https://cloud.githubusercontent.com/assets/5937572/6939894/c1bfd71e-d879-11e4-86a5-acc73d52284e.png)

**Comment by dasilva333** [comment]
Try version 1.3.8 and post a new screenshot if it's still too small for you thanks.
https://github.com/dasilva333/DIM/blob/div-movile-dist/DestinyItemViewer-release.apk

**Comment by Podlesnyy** [comment]
![screenshot_2015-04-03-18-32-33](https://cloud.githubusercontent.com/assets/5937572/6984328/5aaebd5c-da30-11e4-90bc-e13a1e743fe1.png)

**Comment by coasterreal** [comment]
![screenshot_2015-04-03-11-48-50](https://cloud.githubusercontent.com/assets/11743714/6984502/a5a52a14-d9f7-11e4-9c04-561dc5006afe.png)

**Comment by coasterreal** [comment]
![screenshot_2015-04-03-11-48-46](https://cloud.githubusercontent.com/assets/11743714/6984505/af0f534a-d9f7-11e4-8de2-d6725344e972.png)

**Comment by coasterreal** [comment]
I like this - I'm not home to test on my tablet though. I'll need another 5-6hrs.

I have 2 shots just to show that on one, selecting an item near the edge of the screen makes the text go off the screen. No big deal, you can scroll over.

But maybe when you have time, if the text would go off the screen it would know to anchor from right to left instead of left to right. Small detail.

I'm anxious to try on my tablet at home though. Text on phone seems maybe 1pt larger but it helps. Icon size isn't as important but I do like the slightly bigger icons!

Thanks for addressing these issues - I certainly appreciate it.

**Comment by Podlesnyy** [comment]
Another screenshot with data. It's still too small(

![screenshot_2015-04-04-06-33-02](https://cloud.githubusercontent.com/assets/5937572/6991303/af4e5390-da94-11e4-82ee-a637d8145b20.png)

**Comment by coasterreal** [comment]
The icons are fine. The text in the bar across the top is still very tiny.

**Comment by Podlesnyy** [comment]
As for me icons are small. And there is no my third person.

**Comment by dasilva333** [comment]
Try the latest versoin 1.5.1 guys the layout should look much better now and it's user scalable thanks:
https://github.com/dasilva333/DIM/blob/div-movile-dist/DestinyItemViewer-release.apk
Also if you'd like to keep up to date with the latest version use this one:
https://github.com/dasilva333/DIM/blob/div-movile-dist/DestinyItemViewer-release.hydration.apk

**Comment by Podlesnyy** [comment]
Now it's ok. Thanks. Awesome app!
 
![screenshot_2015-04-05-14-36-32](https://cloud.githubusercontent.com/assets/5937572/6996724/67fe6a76-dba1-11e4-8753-f8759da6ea22.png)

**Comment by dasilva333** [comment]
Cool man looks perfect closing the ticket as issue is resolved
