### ISSUE TITLE
Moving between characters doesn't work

### ISSUE THREAD

**Issue by munkt0n** [dasilva333/DIM#18]
Can't seem to be able to move items directly between characters.
eg. Select item from char 2, select 'store' on char 1, item moves to Vault, I then have to move from Vault to char 1
Firefox 37.0, OS X

**Comment by dasilva333** [comment]
Good catch, are you getting Patience is a virtue error message?

**Comment by munkt0n** [comment]
Hi, yes, I get the 'patience is a virtue' dialog each time I try to move an item.

**Comment by dasilva333** [comment]
This was fixed as of 1.4.0 try the latest version please: https://github.com/dasilva333/DIM/blob/div-movile-dist/destiny_item_viewer.xpi

**Comment by munkt0n** [comment]
working perfectly now. thanks for the update
