### ISSUE TITLE
View only 2 out of 3 characters

### ISSUE THREAD

**Issue by akirakurosawa** [dasilva333/DIM#19]
So in the first iteration I was able to scroll down and see the vault first, then all 3 characters.  Now I get the vault, my primary character, and my last created character.  I am missing the second alt I created.  All 3 are hunters.

**Comment by Mulchman** [comment]
Just chiming in to say that I'm experiencing this as well.

**Comment by Mulchman** [comment]
Chrome developer tools window shows the following information (no idea if this is relevant):

The key "target-densitydpi" is not supported.
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/cordova.js Failed to load resource: net::ERR_FILE_NOT_FOUND
app.js:841 false isEmptyCookie true
app.js:847 loadData
bungie.js:2 bungie constructed w null
bungie.js:94 _getToken finished with 6509139896945091855
app.js:684 user finished
6bungie.js:94 _getToken finished with 6509139896945091855
app.js:625 Uncaught TypeError: Cannot read property 'itemName' of undefined

**Comment by Mulchman** [comment]
Saw a comment on issue #20 (https://github.com/dasilva333/DIM/issues/20) relating to it possibly being an item not supported, so here's an album with 2 shots from DIM showing all my items: http://imgur.com/pQixzgK,7yI5Ac5

**Comment by dasilva333** [comment]
Try 1.3.7 for Chrome I patched it with a fix that should take care of it, let me know thanks. https://github.com/dasilva333/DIM/blob/div-movile-dist/destiny_item_viewer.zip

**Comment by Mulchman** [comment]
Still seeing just two characters with the 1.3.7 .zip file version you just linked: http://imgur.com/FHcuwkg

**Comment by DeCoded-Void** [comment]
I am only seeing 1 out of 3 characters on my chrome extension and android, it was working fine this morning...

**Comment by Mulchman** [comment]
In the official Bungie Destiny app, my 4th Horseman is on the character that doesn't get displayed in DIV and it's listed weirdly as "CLASSIFIED" for name and "CLASSIFIED" for type of weapon. The image is a white box. Could this be the problem? I was going to test by trying to move this item to the vault, but the Destiny app encounters errors when dealing with it. I'm not near the PS4, either, so I can't manually move it to the vault or another player.

**Comment by DeCoded-Void** [comment]
Hey, that can be the issue, I have 2 4th horsemans, Both of which are stored in each of the characters that I am missing. I am unable to move my 4th horseman in between my characters in anything including DIM, bungie did fix this issue from the past few weeks, and now, it's back.

**Comment by DeCoded-Void** [comment]
Bungie is doing maintenance on the website, I know this since the forum catagories page does look a bit different. https://www.bungie.net/en/Forum/Categories
Bungie probably messed up the 4th horseman again, this issue had originally appeared when bungie introduced item transferring which was fixed less than a week later, hopefully, bungie will fix this issue in under a day.
When I attempt to transfer my weapon with DIM I get 
Error #1627
The Vendor you requested was not found.

**Comment by Mulchman** [comment]
I made a Bungie dot net post regarding the 4th Horseman: https://www.bungie.net/en/Forum/Post/113113870/0/0

**Comment by Mulchman** [comment]
Think this can be closed now; fixed in #25

**Comment by dasilva333** [comment]
thanks
