### ISSUE TITLE
Progress --> Missing XP is not working

### ISSUE THREAD

**Issue by ChristopherLenz** [dasilva333/DIM#2]
This filter shows nothing for me. For Weapons and Armor.

**Comment by dasilva333** [comment]
Missing XP: Items that do not have their circles completely filled in with XP.

If you're sure you have items that match that criteria try taking a screenshot of a weapon or armor piece that is missing xp with the DestinyDB tooltip included.

Thanks

**Comment by ChristopherLenz** [comment]
if I select the filter no element is shown. And you can believe me. Not all my weapons are "XP-maxed"

unfiltered:
![div_unfiltered](https://cloud.githubusercontent.com/assets/11405586/6846894/4117b340-d3c2-11e4-9315-10c6c82c591a.PNG)

filtered:
![div_missingxp](https://cloud.githubusercontent.com/assets/11405586/6846909/623bdd58-d3c2-11e4-8ef9-8bc565d57536.PNG)

**Comment by dasilva333** [comment]
Good catch! I'll be fixing it soon thanks

**Comment by wein3967** [comment]
This will be an awesome feature for those crazy people like me that hate "wasting" bounty XP. I'm having the same issue; no weapons shown when selecting Missing XP.
![unfiltered 2015-03-26_8-23-06](https://cloud.githubusercontent.com/assets/11590326/6847060/a004bbf4-d391-11e4-9430-d1585ff7a1a5.png)
![filtered 2015-03-26_8-23-22](https://cloud.githubusercontent.com/assets/11590326/6847062/a28b8e16-d391-11e4-8cec-64805ca3ce0e.png)

Really great work here. Love the layout.

**Comment by dasilva333** [comment]
Fix has been added thanks for your help guys you can find the revision here:
https://github.com/dasilva333/DIM/commit/e27565ea1f1e978b1cb1189f9fed4dcf05a9058f

If you installed it from the Chrome Store you'll have to wait until I release 1.0.10 otherwise follow the manual install instructions to install the current build.

**Comment by ChristopherLenz** [comment]
much better ;-). works like a charm

![image](https://cloud.githubusercontent.com/assets/11405586/6847245/54a90cbc-d3c5-11e4-857d-30c3fc53e689.png)
