### ISSUE TITLE
Icons too large with latest update?

### ISSUE THREAD

**Issue by scosaw** [dasilva333/DIM#21]
The item icons are huge now, both in Firefox and Chrome.  Any way to revert to the smaller set?  It's breaking the entire layout of the app, where it was perfect before.

**Comment by dasilva333** [comment]
I'm sorry man I"m trying to get it to work on tablets and phones too expect a change that'll reduce the icon size in desktop I too agree the icons are huge now.

**Comment by dasilva333** [comment]
Try version 1.3.8 it should look better: Chrome:https://github.com/dasilva333/DIM/blob/div-movile-dist/destiny_item_viewer.zip and Firefox: https://github.com/dasilva333/DIM/blob/div-movile-dist/destiny_item_viewer.xpi

**Comment by ssoriche** [comment]
Main icons are still a little big in Chrome, but better. Load out icons are still really big in 1.3.9.

**Comment by WarbirdXBL** [comment]
Hmm, In Firefox 1.3.9 (1.3.8 in the banner) I can see how the interaction with Zoom could complicate the layout bot vs multi-platform compromise.  You might wait until the dust settles from your recent layout change, and them tackle just the worst cases? I am able to get the layout to work using a combination of Zoom and Zoom Text Only.  Its interesting, when zooming in the item images switch to large and then the four main columns wrap.

**Comment by dasilva333** [comment]
If it still looks too big in 1.3.9 then expect a further reduction they're currently 71x71 px at four columns and It used to be at 44px originally perhaps I'll split the difference and have it settle at around 58px each image.

**Comment by scosaw** [comment]
Cool, fixed.  Thanks!
