### ISSUE TITLE
Crashes on iPhone 6 Plus

### ISSUE THREAD

**Issue by OUTFOXEM** [dasilva333/DIM#22]
Once the login popup tries to load Bungie.net, the app crashes every time without exception on my iPhone 6 Plus.  I have tested it on my iPhone 5 and it works with the same version of iOS (8.1).

Not sure if it makes a difference or not, but I made sure I was logged into Xbox.com and Bungie.net on Safari to ensure the cookie is there and that the page can load (I also loaded both the mobile and desktop sites of Xbox.com).

Here are other people reporting the same issue on the reddit thread:

http://www.reddit.com/r/DestinyTheGame/comments/30syh7/discussion_destiny_item_viewer_now_for/cpwg2eq?context=3

**Comment by koko949** [comment]
im also having this exact issue on my iphone 6+, after entering in login credentials in the microsoft account sign in page, it crashes. i have tried turning off my hosts blocker and springtomize 3 tweak.

**Comment by OUTFOXEM** [comment]
Good call on the hosts file.  I removed mine completely to test and same result.

**Comment by dasilva333** [comment]
Alright I'm not sure as for the reason for the crash but I'll be creating a debug build with debug instructions you can follow to help me figure out why this is happening. It'll be based off the 1.3.8 build which you can try here if you haven't already: https://github.com/dasilva333/DIM/blob/div-movile-dist/DestinyItemViewer.ipa

**Comment by koko949** [comment]
1.4 is still crashing for me. how i can run the debug?

**Comment by dasilva333** [comment]
Instructions for OUTFOXEM AND koko949:

Download the debug build for iPhone here:
https://github.com/dasilva333/DIM/blob/div-movile-dist/DestinyItemViewer.debug.22.ipa

Visit this page: http://jsconsole.com/
Type this into the console: :listen 39538077-D0F1-41CC-A8F9-ADF29BB1A66D
Install and open the app, try to get it to crash and report back whatever error messages you get from jsconsole.

**Comment by koko949** [comment]
not sure if its debugging correctly. here are the steps i took....

1. visited jsconsole.com and entered in :listen 39538077-D0F1-41CC-A8F9-ADF29BB1A66D in my safari browser
2. installed debug.ipa
3. ran div
4. checked back on safari and didnt really see anything new. 

im i doing it correctly?

**Comment by dasilva333** [comment]
Yeah that seems correct, try uninstalling the app and reinstalling it if that still doesn't help try installing CrashReporter from Cydia and provide both log files through this service: http://pastebin.com/ or any online paste service. thanks

**Comment by koko949** [comment]
Here's what it brought up. 

remote console.loglink
"found result in loadstop CkTst=G1428081813994; wlidperf=throughput=5&latency=646"
Connected to "39538077-D0F1-41CC-A8F9-ADF29BB1A66D"

<script src="http://jsconsole.com/remote.js?39538077-D0F1-41CC-A8F9-ADF29BB1A66D"></script>
Connected to "39538077-D0F1-41CC-A8F9-ADF29BB1A66D"

<script src="http://jsconsole.com/remote.js?39538077-D0F1-41CC-A8F9-ADF29BB1A66D"></script>
remote console.loglink
"found result in loadstop CkTst=G1428081813994; wlidperf=throughput=5&latency=646"
remote console.loglink
"found result in loadstop CkTst=G1428081813994; wlidperf=throughput=5&latency=646"
remote console.loglink
"found result in loadstop CkTst=G1428081813994; wlidperf=throughput=5&latency=646"
file:///private/var/mobile/Containers/Bundle/Application/6E3FEAF3-AE9D-4067-A8CA-F42BB4FF12C6/DestinyItemViewer.app/www/cordova.js:1109link
TypeError: null is not an object (evaluating 'event.type')
remote console.loglink
"Error in Success callbackId: InAppBrowser589612063 : TypeError: null is not an object (evaluating 'event.type')"
remote console.loglink
"code 99"
remote console.loglink
"true isEmptyCookie true"
:listen 39538077-D0F1-41CC-A8F9-ADF29BB1A66Dlink
Creating connection...
Connected to "39538077-D0F1-41CC-A8F9-ADF29BB1A66D"

<script src="http://jsconsole.com/remote.js?39538077-D0F1-41CC-A8F9-ADF29BB1A66D"></script>

**Comment by koko949** [comment]
let me know if you need anything else. i appreciate you working hard on this. thanks!

**Comment by OUTFOXEM** [comment]
Well I wasn't able to download the debug version (link seems to be out of date), and jsconsole.com and CrashReporter reported nothing.  CrashReporter detected the crash but wouldn't list a cause for it.

I installed syslogd though and have a syslog with a detailed crash report on DIV for you here:

https://fnpaste.com/ZZRP

Hopefully that helps some.  Let me know if there's something else I can do to help.

**Comment by dasilva333** [comment]
Heres the important bits:

> Apr  5 11:45:54 iPhone-6-Plus-64GB ReportCrash[578]: Exception Type:  EXC_RESOURCE
> Apr  5 11:45:54 iPhone-6-Plus-64GB ReportCrash[578]: Exception Subtype: MEMORY
> Apr  5 11:45:54 iPhone-6-Plus-64GB ReportCrash[578]: Exception Message: (Limit 650 MB) Crossed High Water Mark
> Apr  5 11:45:54 iPhone-6-Plus-64GB ReportCrash[578]: Triggered by Thread:  6

Here's one I dont understand:

> DestinyItemViewer[474]: webView:didFailLoadWithError - -999: The operation couldn’t be completed. (NSURLErrorDomain error -999.
> Apr  5 11:45:52 iPhone-6-Plus-64GB DestinyItemViewer[474]: Communications error: <OS_xpc_error: <error: 0x197e8fa80> { count = 1, contents =
> 		"XPCErrorDescription" => <string: 0x197e8fe78> { length = 22, contents = "Connection > interrupted" }
> 	}>

Weird a lot of weird memory issues going on, perhaps you might want to try to see if it opens in safe mode, try looking up how to boot your jailbroken into safe mode and try see if it loads. I'm also going to revisit the loading procedure see if I can help in the matter.

Thanks for the logs

**Comment by OUTFOXEM** [comment]
I have booted in both safe mode and without Substrate (aka non-jailbroken mode).  It crashes in both instances as well at the same point.

Also, since you noted the memory issue, I will mention that Crash Reporter, even though it didn't produce a log, did alert me of low memory right before it crashed.

**Comment by dasilva333** [comment]
I'm closing all the tickets I cant fix in the short term in favor of a new ticket in the new repo if it's still an issue please report any new findings with version 1.6.5 here: https://github.com/dasilva333/TowerGhostForDestiny/issues thank you
