### ISSUE TITLE
Unable to access Heavy during load out creation

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/DIM#24]
While creating a load out in Chrome version 1.3.9, I can not scroll down far enough to access the heavies.

There are other issues that are visible in the screen shot as well.

![screen shot 2015-04-03 at 12 44 48 pm](https://cloud.githubusercontent.com/assets/19838/6985295/dc4e5f60-d9ff-11e4-8a62-0f4928ccbf6a.png)

**Comment by dasilva333** [comment]
thank you man I plan to revisit loadouts and fixing these issues is one of them

**Comment by dasilva333** [comment]
Try on the latest version 1.5.1 and let me know how it goes thanks
https://github.com/dasilva333/DIM/blob/div-movile-dist/destiny_item_viewer.zip

**Comment by ssoriche** [comment]
Working great, thanks!
