### ISSUE TITLE
The toxic 4th Horseman

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/DIM#25]
Can anything be done, in the short term, to allow DIV to work when this weapon is encountered? DIM has no problem displaying the 4th Horseman. It doesn't break the layout or anything. But with DIV, wherever the 4th Horseman is (eg. vault and/or character 1/2/3), that particular section won't show up. It breaks the functionality of the entire extension.

It essentially means, until Bungie fixes the 4th Horseman, users who have the weapon cannot use DIV unless DIV add some special handling for it (like whatever DIM does).

(I'm currently testing/using 1.3.9 (well, it says 1.3.9 in the Chrome extensions window but it says "DIV 1.3.8" when the window opens showing my characters).)

**Comment by dasilva333** [comment]
Hey man thanks for the writeup if possible press F12 in Chrome and paste in here any error messages you see or otherwise. I thought I fixed it with 1.3.7 but apparently it's still a problem. Let me know thanks

**Comment by Mulchman** [comment]
Looks to be the same messages as before, full F12 output:

The key "target-densitydpi" is not supported.
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/cordova.js Failed to load resource: net::ERR_FILE_NOT_FOUND
app.js:850 false isEmptyCookie true
app.js:856 loadData
bungie.js:2 bungie constructed w null
bungie.js:94 _getToken finished with 2180323042057550105
app.js:691 user finished
6bungie.js:94 _getToken finished with 2180323042057550105
app.js:632 Uncaught TypeError: Cannot read property 'itemName' of undefined

**Comment by ssoriche** [comment]
This is the error I'm getting in 1.3.9:

```
app.js:632 Uncaught TypeError: Cannot read property 'itemName' of undefined
app.js:632 processItem
app.js:715 (anonymous function)
app.js:714 (anonymous function)
bungie.js:84 r.onload
```

**Comment by Mulchman** [comment]
Just noticed a 1.4.0 zip, here's the output from it (similar itemName undefined text):

The key "target-densitydpi" is not supported.
chrome-extension://dfikoohpncmijphggmnoefnpcjkkaida/www/cordova.js Failed to load resource: net::ERR_FILE_NOT_FOUND
app.js:850 false isEmptyCookie true
app.js:856 loadData
app.js:691 user finished
app.js:632 Uncaught TypeError: Cannot read property 'itemName' of undefined

**Comment by dasilva333** [comment]
Can you try the new build I just made it should have a fix and some debug output to figure out the issue it turns out the 4th horseman doesn't have a description? Anyhow link is here:
https://github.com/dasilva333/DIM/tree/div-movile-dist

let me know thx

**Comment by Mulchman** [comment]
Uncaught TypeError: Cannot use 'in' operator to search for 'itemName' in undefined

**Comment by dasilva333** [comment]
New version committed, thanks for sticking around and providing a quick turnaround on the results this one should fix it however troubling is that it seems Bungie isn't providing me a definition for the weapon in their response. If this is the case I won't be able to fix it showing until I remove all dependency on the definitions=true param but the profile will still show with the rest of the items.

**Comment by Mulchman** [comment]
Your commit did it. All 3 characters show now. http://imgur.com/X4t7MVF

**Comment by dasilva333** [comment]
Great thanks for the screenshot it seems Bungie indeed does not provide a definition for that weapon. Im closing the ticket until I get rid of the definitions=true dependency. thanks for your help

**Comment by Mulchman** [comment]
Thanks for the fast turnaround!
