### ISSUE TITLE
Vault armor counts wrong

### ISSUE THREAD

**Issue by seansli** [dasilva333/DIM#26]
Hello!

I've been using this for about a week now - first of all, many thanks for this great fork; it's super useful, and well organized.

Right now, I've having an issue where I don't think I have armor in the vault, but it shows counts for the armor:

https://www.dropbox.com/s/l2fzd82vwqitaz5/Screenshot%202015-04-03%2018.19.58.png

The counts on the left should all be zero, no?

**Comment by dasilva333** [comment]
Good catch thanks I'll be fixing that today

**Comment by dasilva333** [comment]
Try version 1.5.1 and report back if it's been fixed thanks
https://github.com/dasilva333/DIM/tree/div-movile-dist

**Comment by dasilva333** [comment]
Alright I know I said I fixed it in 1.5.1 but it's /really really/ fixed as of 1.5.3 report back so I can close the ticket thanks

**Comment by seansli** [comment]
Yup - looks fixed to me. Thanks!
