### ISSUE TITLE
Loadout items are filtered too

### ISSUE THREAD

**Issue by matthubb** [dasilva333/DIM#27]
Display filter should not apply to loadout items?

I was just trying out 1.4.1 from the Chrome Store on Chrome. Started a new loadout for Arc weapons, added a shotgun and Murmur and then had trouble hunting for the rest of the items I wanted, so I filtered by arc damage and Murmur disappeared from the loadout section until I cleared the filter.

This didn't seem the right thing to happen to me, but I guess you could argue either way.

**Comment by dasilva333** [comment]
Thanks for the bug report, that's going to be a trick bug to fix I would agree that it shouldn't go away.

**Comment by dasilva333** [comment]
this should be fixed as of 1.6.4 please confirm and close ticket thank you

**Comment by dasilva333** [comment]
Sorry I spoke too soon it'll be fixed as of 1.6.5

**Comment by dasilva333** [comment]
Closing ticket as problem is fixed, if you feel if it's still an issue please report any new findings with version 1.6.5 here: https://github.com/dasilva333/TowerGhostForDestiny/issues thank you
