### ISSUE TITLE
Class items not Showing

### ISSUE THREAD

**Issue by klefto3** [dasilva333/DIM#28]
Cloaks, Bonds and Marks are missing.

**Comment by dasilva333** [comment]
Shows up for me as of 1.5.7: http://i.imgur.com/jqalLhu.jpg
Please try the latest version and report back the results:
https://github.com/dasilva333/DIM/tree/div-movile-dist

**Comment by klefto3** [comment]
I'm not sure how to get the latest version.

**Comment by dasilva333** [comment]
Considering problem fixed, please follow the install instructions provided here: 
https://github.com/dasilva333/DIM
or here:
http://www.reddit.com/r/DestinyTheGame/comments/316hx4/discussion_destiny_item_viewer_for/

**Comment by klefto3** [comment]
got it to load.  awesome.  thank you very much!
