### ISSUE TITLE
Option to auto equip load out

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/DIM#29]
Is it possible to add an option to a load out to have it auto equip?

For example when running sword, I want my Mask of the Third Man, specific chest armour, Red Death, Sword Breaker, and Hunger of Crota equipped.

There's probably a way to automate based on single weapons/armour in each class, but I think a checkbox to toggle the option would be a simpler solution.

**Comment by dasilva333** [comment]
Agreed, I'll be doing both the options so you can select which one in your loadout will be equipped. Thanks for filing it as an issue

**Comment by dasilva333** [comment]
I'm going to close this ticket and add it to the new repo under the Wiki instead, move all the suggestions there so they can be easily tracked. thanks for the feedback
