### ISSUE TITLE
Option to disable Auto Refresh

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/DIM#3]
When unchecking auto refresh and forcing a reload, the auto refresh box gets rechecked.

Need a way to set auto refresh off and have it persist, but also the ability to force a refresh without clicking the browser reload.

**Comment by dasilva333** [comment]
Functionality added to latest revision expect to see it in version 1.0.10 in Chrome

**Comment by dasilva333** [comment]
This functionality has been added, if you would like to confirm and close ticket you can do so now.
