### ISSUE TITLE
Weird graphics in Load Outs TDG 1.6.1 Chrome Extension

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/DIM#30]
When the load out panel opens, there are some strange graphics in it.

![screen shot 2015-04-06 at 3 25 17 pm](https://cloud.githubusercontent.com/assets/19838/7010885/b340c098-dc72-11e4-99f6-d383ebd917bd.PNG)

This happens with every load out.

Chrome version 41.0.2272.118 (64-bit) on OS X.

**Comment by ssoriche** [comment]
Just as an update, creating a new load out has the same results.

**Comment by ssoriche** [comment]
Another update, occurs in the iOS version too.

![image1](https://cloud.githubusercontent.com/assets/19838/7015468/7448c91e-dca2-11e4-9eb7-8ede486bd312.PNG)

**Comment by chrisdudek** [comment]
Looks like this is corrected in latest build (1.6.3) for both Chrome and iOS. Icons look much better. Now the text for the Class Name (Hunter/Warlock/Titan) overlaps the emblem. Might look a little cleaner if the text was on top of the emblem. But overall very nice change - makes it much easier to read and use.

**Comment by dasilva333** [comment]
text overlap and graphics issue fixed, please open a new ticket if it's still an issue in 1.6.5 here: https://github.com/dasilva333/TowerGhostForDestiny
