### ISSUE TITLE
Shaders and Emblems in Load Outs

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/DIM#31]
Started creating a load out for Iron Banner including the Million Million shader and the Emblem.

The shader shows as no image in the loud out, and the emblem refuses to be put into a load out.

![screen shot 2015-04-06 at 3 50 41 pm](https://cloud.githubusercontent.com/assets/19838/7011146/b748cf30-dc74-11e4-96eb-75b89b8ac7be.PNG)

**Comment by dasilva333** [comment]
problem fixed for loading stuff in Other into your loadouts

**Comment by dasilva333** [comment]
problem fixed as of 1.6.4 please confirm and close ticket thank you

**Comment by ssoriche** [comment]
Yes it it fixed. Thank you.
