### ISSUE TITLE
Layout Issues in Chrome

### ISSUE THREAD

**Issue by FreakBurrito** [dasilva333/DIM#33]
When opening the extension, there is a lot of wasted layout space, In addition, it would be cool if the categories locked to each others vertical positions, so that the same categories are lined up with each other.

![tgd_1_6_1_entry_screen](https://cloud.githubusercontent.com/assets/7030390/7015247/cc23301a-dc9e-11e4-9f4b-9a9600c713a1.png)

The new location of the transfer bar feels awkward on a maximized browser window.

![tgd_1_6_1_transfer](https://cloud.githubusercontent.com/assets/7030390/7015246/cc09f492-dc9e-11e4-8e17-a807adb44c10.png)

I love the new features that have been added, like the quantity transfers for materials, but the rapid version releases are a bit disconcerting. It feels like every day I've opened the extension and there is something new added, and several new broken things. This is hands down the best organised item manager for Destiny, but it would be nice to see some stability in it's development process.

**Comment by seansli** [comment]
Or a changelog that pops up, so we know what to expect! :)

**Comment by dasilva333** [comment]
First of all nice collection bro, thanks for the feedback I'l be making improvements based on your comments thank you

**Comment by dasilva333** [comment]
Problem fixed as of 1.6.7 please confirm and close ticket 
https://github.com/dasilva333/TowerGhostForDestiny/tree/div-movile-dist

**Comment by FreakBurrito** [comment]
I'll be at work for another few hours, I'll confirm when I get home.

**Comment by FreakBurrito** [comment]
looks good!
