### ISSUE TITLE
Emblem text misaligned

### ISSUE THREAD

**Issue by wickles** [dasilva333/DIM#34]
The title covers the text saying "Emblem", pretty simple. 

![screen shot 2015-04-06 at 8 17 17 pm](https://cloud.githubusercontent.com/assets/4229542/7016485/108f5f08-dc9a-11e4-820c-59aa62e5e3c1.png)

**Comment by dasilva333** [comment]
Good catch that's an easy fix, I'm not sure if i should get rid of the "emblem" label all together or have it move up. Thanks for the bringing it up

**Comment by dasilva333** [comment]
problem fixed as of 1.6.4 please confirm and close ticket

**Comment by wickles** [comment]
Works fine now, thanks!
