### ISSUE TITLE
iOS Beta 2 - Tooltip Alignment

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/DIM#35]
![image](https://cloud.githubusercontent.com/assets/11835064/7022935/a091eb0a-dcf6-11e4-9065-88ceca697866.jpg)

When using the tooltip feature, the image displayed is a little off-centered, causing the left side to be cut off as seen in image. Also - how do you use the tooltip and also move the item on the app? Right now it appears to be one or the other. It would be great if double tapping on the icon brought the tooltip and single tapping allowed you to move it.

Hardware: iPhone 5s
Software: iOS 8.2 ; TGD 1.6.2

Thanks!

**Comment by dasilva333** [comment]
double tapping brings up the tooltip and single tap brings up the transfer popup.
single tapping the popup closes it, clicking anywhere else closes the transfer popup
I'm aware of the cutting off I'll look into having it resize if it doesn't fit the screen but it's not my code so I'm not sure how easy it'll be to do.

**Comment by chrisdudek** [comment]
Thanks for the quick reply and explanation. 

For me, single tapping is bringing up to the tooltip and the transfer options. Tooltip covers transfer. Just realized I can scroll down and the transfer box stays at the bottom of the screen and the tooltip moves up. Not a big deal now that I know how to get to the transfer options. Just wanted to give you a heads up.

**Comment by chrisdudek** [comment]
You can probably disregard the single/double tapping issue. It only occurs when you go into settings and click on "Destiny DB Tooltips" (so it is highlighted). If it is not selected, the single and double tapping work exactly as you mention, which is slick.

**Comment by chrisdudek** [comment]
I can confirm it looks good now in iOS 8.2, TGD 1.6.4. iPhone 5S.

**Comment by dasilva333** [comment]
Great thanks for the confirm I too agree it looks good on my iPhone 5s too closing ticket
