### ISSUE TITLE
[Android] Sub-menus stop working after 15-20 seconds

### ISSUE THREAD

**Issue by dn4cer** [dasilva333/DIM#36]
Hello, 

Using the BlackBerry Z30 to run the Android app. I am affected by the keyboard disappearing glitch, but can get around it by turning off the LoadListener (as it indicates in the initial screen). However, once I'm logged in, all of the sub-menus stop working after 15-20 seconds. For example, I'll tap on 'Settings' and nothing will happen.

If I restart the app, the menus work for about 10-15 seconds, but after that they completely stop working.

I should mention, I'm using version 1.6.3 of the app.

**Comment by dasilva333** [comment]
I am going to leave this issue open until I can provide you with a jsconsole debug version of the app with instructions on how to test it. Stay tuned and thanks for the bug report.

**Comment by dasilva333** [comment]
I'm closing this issue in favor of a new one with instructions on what you can try to debug it, please visit this link @dn4cer  and follow it to help me fix the problem for you thanks

https://github.com/dasilva333/TowerGhostForDestiny/issues/3
