### ISSUE TITLE
1.6.3 showing duplicates of every character & vault

### ISSUE THREAD

**Issue by DrPippin** [dasilva333/DIM#38]
Just updated to 1.6.3 through hydration, and immediately upon signing in I am seeing two vaults (both identical), and two of each character (each of them are identical to their twin).  Running on an iPhone 5 with iOS 8.

![image](https://cloud.githubusercontent.com/assets/5474991/7032565/16a80120-dd39-11e4-9881-d444756b4e2a.png)

**Comment by DrPippin** [comment]
Oops, failed to mention this was on iOS 8.

**Comment by DrPippin** [comment]
Apparently going to "settings" -> "refresh items" clears this bug.

**Comment by dasilva333** [comment]
As a temporary workaround use Refresh Items, I will have to actually fix the bug thanks for opening a ticket

**Comment by dasilva333** [comment]
Problem fixed in the next version 1.6.4 thanks

**Comment by dasilva333** [comment]
Problem has been fixed as of 1.6.4 you can't cause this to happen anymore, please confirm and close thanks

**Comment by DrPippin** [comment]
Just updated through hydration to 1.6.6 on iOS, and the double vault/characters is occurring again.

**Comment by dasilva333** [comment]
Try 1.7.2 and let me know if it's still happening. thanks a lot for your help in testing

**Comment by DrPippin** [comment]
Updating to 1.7.2 has resolved the issue.
