### ISSUE TITLE
Adjustments to Loadout Section/Workflow

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/DIM#39]
1. It would be great to be able to Close or Cancel the loadout section without having to go to the hamburger icon --> Loadouts --> Close. Maybe add a button under "Delete" in iOS build.

2. When creating a loadout, it would be helpful to have the weapons better organized. Rather than breaking them up by where they are (vault/characters), place all Primaries together, Specials together, Heavies together. For armor, it makes sense to break them up by Character. No need for Vault section in either instance. Or if you can come up with a better idea, I'm all for it.

3. When creating a loadout, I can't select the items at the bottom. The loadout section covers them up, making them inaccessible.

I think you mentioned you're working on the loadouts workflow as a whole, so I thought I would throw my 2 cents in there. Right now, I think it works great if the loadout is already created (maybe on browser) and then you're only using mobile to equip.

iPhone 5S running iOS 8.2, TGD 1.6.3 Hydration enabled.

Thanks!

**Comment by chrisdudek** [comment]
Since this is more related to suggestions than bugs, please let me know if I should redirect these items to reddit and close this out.

**Comment by dasilva333** [comment]
no it's fine
1. Cancel button added to loadouts for next version
2. this will be a more long term thing it fits better elsewhere
3. problem fixed in the next version

thanks for your feedback

**Comment by chrisdudek** [comment]
You're the man! Thanks again. I'm about to start raids and nightfalls. Using your app like a fiend!

**Comment by dasilva333** [comment]
fixed as of 1.6.4 please confirm and close the ticket thanks

**Comment by chrisdudek** [comment]
Confirmed. Closing.
