### ISSUE TITLE
Refresh causing search results to disappear

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/DIM#4]
About 3 seconds after submitting a search, the inventory refreshes and the search results are lost.

**Comment by dasilva333** [comment]
Good find, I recently introduced this bug I didnt realize I broke it in 1.1.3 after revamping the toolbar thanks expect the fix in the next version (1.1.5)

**Comment by ssoriche** [comment]
Just updated and this is now fixed. Thank you.
