### ISSUE TITLE
Transfer items menu won't open

### ISSUE THREAD

**Issue by purepvd** [dasilva333/DIM#40]
The configured loadout in the image won't open the transfer items menu on my hunter but will on my warlock and titan. If I remove any one item from the loadout the transfer items window will open. It's not specific to special weapons or my hunter (based on this happening on other characters with different loadouts). I can't seem to isolate the issue any further than that. This was happening on 1.6.0 windows phone version so I tried 1.6.2 chrome extension and found the same thing going on.

![image](https://cloud.githubusercontent.com/assets/3674827/7036125/2dac1ab2-dd5e-11e4-9781-646ff15ca36a.png)

**Comment by dasilva333** [comment]
This problem already reported in issue #30 feel free to post any additional feedback there. thanks

**Comment by purepvd** [comment]
Thanks, I'll report back if the issue still exists in 1.6.3

**Comment by purepvd** [comment]
Tried in 1.6.6 and this is still happening. Tried debugging it some and found it isn't a layout problem. Seems like it tries to find a swap item in this part of the code but swapItem is null here. Tries to access swapItem.description and throws an unhandled exception. Not sure why it happens though...there is probably no available item to swap with at this point but I don't think it should need one to swap with if there are enough open slots.

![image](https://cloud.githubusercontent.com/assets/3674827/7060099/309eb7b6-de49-11e4-9229-0dc19815907e.png)
