### ISSUE TITLE
Kinetic Damage Filter

### ISSUE THREAD

**Issue by matthubb** [dasilva333/DIM#43]
With the Chrome Store TGD version (1.6.4), using the Kinetic Damage Filter hides all weapons except for Murmur.

Expected to see all non-elemental weapons.

**Comment by dasilva333** [comment]
problem fixed expect to see it in the next version thank you for bringing it up to me

**Comment by dasilva333** [comment]
Problem fixed as of 1.6.5, please manually install Chrome found here:
https://github.com/dasilva333/DIM/tree/div-movile-dist/
and report back if it worked thanks
https://github.com/dasilva333/DIM/
Install instructions

**Comment by matthubb** [comment]
Just cloned at TGD 1.6.6.

Burn - Kinetic works as expected. Thanks! Closing
