### ISSUE TITLE
[Feature Request] Ability to move equipped gear

### ISSUE THREAD

**Issue by dn4cer** [dasilva333/DIM#44]
Right now this is not possible.
Ideally, I'd like to be able to move equipped items to another character.
I know that there's a bit if complexity around doing this, but I think it's entirely possible.

Steps I think could be followed to make this happen.
Acronyms:
FG - From Guardian - Moving item from this guardian
TG - To Guardian - Moving item to this guardian
I'll be using these below.

1. If the item we are moving is an Exotic, attempt to switch it out with a different exotic. If there are no other exotics on the FG, then lesser quality piece of gear starting with Legendary.
2. If the item we are moving is not an exotic, first check to see if there as another exotic equivalent (armor piece or weapon) equipped. If not, replace the item with an exotic, if none present, then equip a lesser quality piece of gear.
3. This step applies both to steps 1 and 2. If no other piece of gear is on the FG, attempt to move one from the vault and if none in vault, look on other guardians. If user has no other characters, error out
4. After equipped a different piece of gear, move the target piece to the TG using the same logic you currently use.

I know, this might be a little bit of work to implement but entirely possible.

**Comment by dasilva333** [comment]
It currently is possible, I tested it myself on 1.6.4 if you take an equipped item and use the transfer menu to click on any option available it works as expected. Closing ticket as this isn't a bug.
