### ISSUE TITLE
[Suggestion] Android - Postmaster items have Postmaster icon overlay

### ISSUE THREAD

**Issue by Soundwave004** [dasilva333/DIM#45]
Observed:
Weapons & Armor in the Postmaster's inventory show up in the player's inventory, causing the player to erroneously  think they have that item on their person 

Suggestion:
Place the Postmaster's icon over any Weapon/Armor item that is in the Postmaster's possession. 
This way, the player knows where these items actually are.

**Comment by dasilva333** [comment]
Closing ticket, as Post Master items belong in the Post Master section in Other/Misc/Post Master. I dont want to mix post master items into your regular bucket otherwise it'll really mess with the look of the app. Thanks for your feedback I'll leave issue #46 open so I can fix the bug

**Comment by Soundwave004** [comment]
Makes sense. 
Verified as closed. 
Thank you!
