### ISSUE TITLE
[Suggestion] Android - Postmaster items are moved to the "end" of inventory lists 

### ISSUE THREAD

**Issue by Soundwave004** [dasilva333/DIM#46]
Observed:
Weapons/Armor in the Postmaster's inventory are shown at the beginning of the player's respective inventory. 

Suggesting:
Weapons/Armor in the Postmaster's inventory are shown at the end of the player's respective inventory.

**Comment by dasilva333** [comment]
Post Master items belong under Post Master section under Other/Misc/Post Master. there is a known issue where the counts are wrong so I'll leave this ticket open so I can get that fixed thanks for your feedback

**Comment by dasilva333** [comment]
Problem fixed as of 1.6.6 please try it out and let me know thanks

**Comment by dasilva333** [comment]
No update from OP, closing ticket as it has been confirmed fixed

**Comment by Soundwave004** [comment]
Makes sense. 
Verified as closed. 
Thank you!
