### ISSUE TITLE
[Suggestion] Android -  move main menu from top right to top left 

### ISSUE THREAD

**Issue by Soundwave004** [dasilva333/DIM#47]
Observed: 
main app menu is on the top right corner of the app

Suggestion:
moving the app menu to the top left would make it fall more in line with the more modern Android Material design language

**Comment by dasilva333** [comment]
Not going to change, bootstrap designed it to be on the right side. I don't think it'll be a trivial change and I want to focus on bug fixes before I start making more visual improvements. Also created a new repo where issues can be created here: https://github.com/dasilva333/TowerGhostForDestiny/

thanks for your feedback
