### ISSUE TITLE
Auto-Hide Main Menu After Selecting Loadout for Mobile

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/DIM#48]
Suggestion: after selecting an option under Loadout (Create, or the name of a saved Loadout), show the Loadout section at bottom and hide the main menu. 

Right now, after you hit create or select the loadout you want, you have to hide the main menu (hamburger button) before you can really perform another action. 

Much more efficient to auto-hide this menu so the end user can go right into their next step. 

Thanks!

**Comment by dasilva333** [comment]
Please open new issues in the new repo https://github.com/dasilva333/TowerGhostFordestiny/issues/

This isn't a suggestion it's actually a bug bc the menu auto hides in the browser it should also auto hide in the mobile platform. thanks for your feedback

**Comment by chrisdudek** [comment]
Moved to new repo
