### ISSUE TITLE
Trouble with Tower Ghost on Kindle Fire HDX

### ISSUE THREAD

**Issue by ebridwell89** [dasilva333/DIM#54]
Hello,

I am a huge fan of your Tower Ghost for Destiny app as it is the only app of its kind that is available on the Windows Phone platform. I have no troubles with the app on my Windows Phone even while running the Windows Phone 10 developers preview!!! Great Work!!!

My trouble now is that while the app installs and updates fine on my Kindle Fire HDX, it seems to get locked up while trying to sign in to my bungie account. It brings me to bungie.net, and the website loads fine, but then the browser never closes in order for me to use the apps features...it just stays on bungie.net

Any Suggestions? My Kindle is updated to its newest firmware also so I am at a loss as to why your app works perfectly on my Windows Phone, but struggles on my Kindle Fire HDX.

Thank you for your time and I hope to hear from you soon!

Eric

**Comment by dasilva333** [comment]
It's a known issue see here: 
https://github.com/dasilva333/TowerGhostForDestiny/issues/58

Also please do not create any new issues in the old DIM repo and only use the new TGD repo for creating new issues. Thanks for your feedback
