### ISSUE TITLE
Cannot Sign in to XBL on iOS

### ISSUE THREAD

**Issue by drinkc0ke** [dasilva333/DIM#55]
Every time I start the iOS app or go to Settings > Live Login, I receive the error "Error loading inventory {"error":true}." This occurred both before & after today's Hydra update, and my friend with iOS is experiencing the same issue with his XBL account.

Both of us were & are using saved login credentials. I tried locating the Log Out button in the menu, but it appears to have been removed at some point. Additionally, the Bungie page closes too fast for me to log out via the site. I tried going to Bungie in Safari and found my account was logged out already, though I logged in & logged out successfully before trying again, finding that there was no effect. Note that I force closed the app for each login attempt.

I am running an iPhone 6 with iOS 8.3 and my friend is running an iPhone 5C with iOS 8.3. Both of us have only one XBL account & no PSN accounts.

Let me know if you need more information. Thanks!

**Comment by dasilva333** [comment]
try 2.6.8 and next time post an issue in the right TGD repo not DIM repo found here:
https://github.com/dasilva333/TowerGhostForDestiny

**Comment by drinkc0ke** [comment]
Working now as of the latest update. And will do--didn't realize there was a TGD repo. Thanks!
