### ISSUE TITLE
Unable to access loadout on Mac Firefox

### ISSUE THREAD

**Issue by unkownlabs** [dasilva333/DIM#6]
--DIV Icon does not show
--Have to access it manually
resource://jid1-lecsmv0nvgnc2g-at-jetpack/destiny_item_viewer/data/window.html
--Tried to sign into bungie.net and do a refresh on the loadout page, does not load.

Used both 1.2.4 and 1.2.7

**Comment by dasilva333** [comment]
Try the latest version and report back please and thank you

**Comment by unkownlabs** [comment]
Tried the 1.4.2 with
resource://jid1-lecsmv0nvgnc2g-at-jetpack/destiny_item_viewer/data/index.html
Still cannot see the link and the icon, 
I tried manually converting the xpi to zip and logging in manually to psn, no worky

which loads this
http://i.imgur.com/vY01uv8.png


it is also weird with this link
jar:file:///Users/Username /Library/Application%20Support/Firefox/Profiles/vxfe47k7.default-1426520262739/extensions/jid1-Lecsmv0nvgnC2g@jetpack.xpi!/resources/destiny_item_viewer/data/index.html

which loads this
http://i.imgur.com/IE3vwa5.png

**Comment by unkownlabs** [comment]
Oh btw the chrome plugin 1.4.2 works just fine, everything loads including button.

**Comment by unkownlabs** [comment]
Sorry for the inconvenience I caused.

**Comment by dasilva333** [comment]
I'm closing all the tickets I cant fix in the short term in favor of a new ticket in the new repo if it's still an issue please report any new findings with version 1.6.5 here: https://github.com/dasilva333/TowerGhostForDestiny/issues thank you
