### ISSUE TITLE
Progress filters don't work on Armor

### ISSUE THREAD

**Issue by dn4cer** [dasilva333/DIM#7]
When setting the view to "Armor", the progress filters do not work for armor.

The only filter that works is "All".

**Comment by dasilva333** [comment]
Problem was fixed as of 1.2.7 make sure you are running the latest:
https://github.com/dasilva333/DIM/commit/effa8f8e16b7f0d7f5a9984cc7e61834fd017c03
If you are on Firefox use this XPI: https://github.com/dasilva333/DIM/blob/mixed/destiny_item_viewer.xpi
If you are on Chrome use this https://github.com/dasilva333/DIM/blob/mixed/destiny_item_viewer.zip

If you are downloading it from the Chrome/FF Store please wait until I can update them to the latest version. Thanks

**Comment by dn4cer** [comment]
Oh. I am using the Chrome Extension. Haven't tested this in the APK yet. Thanks for the quick update though.

**Comment by dn4cer** [comment]
Loaded the zip you provided. No problems with it except for "Uncaught ReferenceError: ko is not defined" seen in the Extensions page on Chrome. When I view details, I see this line referenced.

```
ko.bindingHandlers.moveItem = {
    init: function(element, valueAccessor, allBindings, viewModel, bindingContext) {
		$(element).bind("click", moveItemPositionHandler(element, viewModel));
    }
};
```

Not sure if this warrants repoening this issue or not, since functionally, I don't see any issues, so will leave closed for now.
