### ISSUE TITLE
Top bar expands and covers "vault" and class name text on low resolutions

### ISSUE THREAD

**Issue by QuintenJohnson** [dasilva333/DIM#9]
I usually split my chrome window to half my screen, so a resolution of 960x1080. At this width and lower, the top bar expands to accept the refresh interval and covers the vault and class name text.

**Comment by dasilva333** [comment]
A screenshot would help a lot, expect a fix once I can see the problem. Also the layout is going to receive improvements as I add support for the mobile platforms too.

**Comment by QuintenJohnson** [comment]
![div](https://cloud.githubusercontent.com/assets/4740332/6904585/7063f956-d6e7-11e4-9262-2c6d8fff92f8.png)

**Comment by dasilva333** [comment]
Try it on the latest version 
https://github.com/dasilva333/DIM/blob/div-movile-dist/destiny_item_viewer.zip
Feel free to close the ticket if the issue was resolved for you
